spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quizdb
    username: root
    password: AaSsLlKk@1209
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  devtools:
    add-properties: false
    remote:
      restart:
        enabled: false
  main:
    lazy-initialization: true
    log-startup-info: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: chuvuz04112001@gmail.com
    password: hdxivtjoraxkzpyl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always

logging:
  level:
    web: WARN
    org:
      springframework:
        boot:
          autoconfigure: WARN
file:
  upload-dir: uploads/
